### ISSUE TITLE
I want to build in the latest environment (Studio).

### ISSUE THREAD

**Issue by Hokoshi** [u-blox/Android-u-blox-BLE#10]
Sorry
I'm quite a beginner in Java.
I installed Android Studio to study SPS and tried to build it. 
I clicked "rebuild", but it didn't work with the following error.

![image](https://github.com/user-attachments/assets/98326ca5-bba3-40a2-aa83-348825b7085b)

I'm at a loss because there are no other examples of SPS being implemented.

**Comment by perssonmagnus** [comment]
Hi Okoshi-san, 

This repo was built using Android Studio 4.2.2 and with SDK version 29 (Android 10). The new SDKs seems to have changed some of the requirements for build files so there is some work to upgrade to the latest version.

The main problem with building for the latest SDKs seems to be related to the Android Mesh library from Nordic Semiconductor, that is used as a submodule. It seems to be a bit problematic to upgrade as it has changed structure somewhat. The easiest way to build this with the latest SDK seems to be to erase this library and remove all mesh-related code from the source. 

Best Regards,
Magnus

**Comment by CoanLuciano** [comment]
Excelent! I removed all mesh related code and could run:

Android Studio Ladybug | 2024.2.1 Patch 1
Build #AI-242.23339.11.2421.12483815, built on October 10, 2024
Runtime version: 21.0.3+-12282718-b509.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.5.0-26-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation

**Comment by perssonmagnus** [comment]
Great news! Thanks for the update.
