### ISSUE TITLE
The scan speed is a little slow

### ISSUE THREAD

**Issue by wenge8n** [u-blox/Android-u-blox-BLE#3]
Hi,
First of all, thank you for your great project.

I checked your code and app on google store.
When scan sensor, sometimes it finds sensor quickly and sometimes it takes very long.
But the iOS app works fine.
Do you have any idea about this problem?
I would be happy to hear back from you.

Thank you.

**Comment by perssonmagnus** [comment]
Hello sir,

We are not aware that the iOS version would be any faster than the Android, but it is very possible that the scanning is run with different parameters on iOS, but we don't think so.

Have you tried the latest version with filtering functionality? It could be that the scan results appear faster using filters.

Best Regards,
Magnus

**Comment by wenge8n** [comment]
Hi,

Thanks for your reply. I think this is not an issue and as you wrote, the scanning runs with different parameters on android and ios so this is device special problem.
I will close this issue.

Thank you
