### ISSUE TITLE
meshprovision project not found

### ISSUE THREAD

**Issue by hemtri1984** [u-blox/Android-u-blox-BLE#4]
While building this project, I am receiving an error:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :meshprovision.
     Required by:
         project :app
      > No matching configuration of project :meshprovision was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.

I am unable to find this meshprovision library whiles its path is added in settings.gradle.

**Comment by ubloxSongYang** [comment]
The problem is that building is messed up by Nordic removing a SHA1 from their Repo. Please follow below steps to check out a nearby SHA1 before fixing this issue.
git clone https://github.com/u-blox/Android-u-blox-BLE.git
cd Android-u-blox-BLE/
git submodule add  https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library.git
cd Android-nRF-Mesh-Library/
git checkout 4b29037
Open project in Android Studio, do a gradle plugin update and add the following line to gradle.properties:
android.useAndroidX=true

**Comment by hemtri1984** [comment]
Now its building the code, but not able to scan the bluetooth. Scan progress bar seems to be running for indefinite time, but not showing any of the bluetooth device in list. 
Problem seems to be with the version of 4b29037 commit of mesh library. 
Please find the attached screenshot for more detail. 
![Screenshot_20210502-123941_u-blox Bluetooth Low Energy](https://user-images.githubusercontent.com/13591768/116800885-15650580-ab44-11eb-990f-e7d695e37435.jpg)

**Comment by perssonmagnus** [comment]
Sorry about the delay. I hope to have some feedback for you on this later this week.

**Comment by perssonmagnus** [comment]
Hi,

In order to get around the Scan issue could you try to set the location permission to ACCESS_FINE_LOCATION, see https://github.com/u-blox/Android-u-blox-BLE/blob/master/app/src/main/java/com/ublox/BLE/activities/DevicesActivity.java#L43.

Best Regards,
Magnus

**Comment by hemtri1984** [comment]
Hi Magnus,

Thanks for the response.

I cross checked that ACCESS_FINE_LOCATION permission has already been set in the mentioned file. I think its already a part of your github code.

However, I have also tried to add these permission into manifest file, but still the application is not able to scan the bluetooth devices.

![Screenshot from 2022-09-18 21-14-56](https://user-images.githubusercontent.com/13591768/190901257-971ecf0a-8217-463a-8243-5d17a8d5cbd4.png)

![Screenshot from 2022-09-18 21-31-34](https://user-images.githubusercontent.com/13591768/190901274-39da364a-c30f-4911-8107-5797965e9e0e.png)

**Comment by hemtri1984** [comment]
However, I suspect that **BluetoothLeService.java** class not inheriting the Service class could be an issue. 
https://github.com/u-blox/Android-u-blox-BLE/blob/master/app/src/main/java/com/ublox/BLE/services/BluetoothLeService.java

The reason is, in your setup guidelines you have instructed to register this class as a service into the manifest file, as
`<service android:name="com.[yourcompany].[yourapp].services.BluetoothLeService" android:enabled="true" />`

While doing this, I found it is giving error, which is because this is not considered as a Service until you do not import Service class into it.
Hence, I tried to complete this step by extending Service class, but this requires the implementation of **onBind** interface, which can be done by vendor program only.

Hence would you mind looking into it. And without inheriting Service class into BluetoothLeService.java, the above required step cannot be accepted by manifest file. (screenshots attached for more details).

Hope this helps.

Kind Regards,
Hemant

![Screenshot from 2022-09-04 11-04-19](https://user-images.githubusercontent.com/13591768/190901647-61f1a644-aded-414c-80de-a08df3f32b9d.png)

![Screenshot from 2022-09-04 11-04-13](https://user-images.githubusercontent.com/13591768/190901663-f3fb3144-b1e4-41a6-af6f-4894373aa98e.png)

![Screenshot from 2022-09-05 00-27-24](https://user-images.githubusercontent.com/13591768/190901672-98dc9768-1fcc-4950-87af-d06081b8ddca.png)

**Comment by perssonmagnus** [comment]
We have just pushed an update to this repo that in our testing solves the issues. Please test this.

**Comment by hemtri1984** [comment]
Back to base now! Facing the same meshprovision error, that was in start.

if I try to resolve meshprovision error, as mentioned initially (above conversation), it will not search for the bluetooth. And the error loop started again.

Is there any specific gradle version or Android studio version you are using?

FYI I am using gradle 7.0.4 (latest version)

![Screenshot from 2022-09-27 22-59-23](https://user-images.githubusercontent.com/13591768/192540073-2f664519-b041-4a39-ad48-02395c5c9d7c.png)

**Comment by hemtri1984** [comment]
However, I am still trying to understand, how this step can work until we do not inherit Service class on BluetoothLeService class? Or this step is not mandatory and obsolete?

![Screenshot from 2022-09-18 21-56-02](https://user-images.githubusercontent.com/13591768/192540543-8b8c421f-14b1-4a5d-9cd9-cb18e11ee6ec.png)

**Comment by perssonmagnus** [comment]
Hi,

The BluetoothLeService class only needs to inherit the Service class if it is used as a Service, which is not the case with the u-blox application, so this is not needed in our case. The README is obsolete and misleading, and we will update this.

The Mesh version should be OK if you download the latest version, git clone --recursive https://github.com/u-blox/Android-u-blox-BLE.

I have tested using both the 4.2.2 version of Gradle that is set in the project and upgraded to 7.4, and they both work fine for me.

**Comment by perssonmagnus** [comment]
Also, the Manifest needs
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />`

which is not reflected in the README, but in the manifest file used.

**Comment by hemtri1984** [comment]
Its working now!! Thank you :)

**Comment by perssonmagnus** [comment]
Working now.
