### ISSUE TITLE
Help on building the BLE project

### ISSUE THREAD

**Issue by MarinusSn** [u-blox/Android-u-blox-BLE#7]
Hello. I've downloaded the BLE code. and tried to build it in Android Studio 4.1.1. But I receive many errors.
Can I get some assistance on how to compile this code?

I need to see how the connection to the SPS service is done. My plan is to see how this is done in debug miode.

Marinus

**Comment by MarinusSn** [comment]
I managed to build the project by following advice given to another user. Thanx

**Comment by perssonmagnus** [comment]
Great!
