### ISSUE TITLE
2.9.2 not work in samgsung S22

### ISSUE THREAD

**Issue by haso2007** [u-blox/Android-u-blox-BLE#9]
But the previous one 2.9.1 and the older 2.6.0 works. Please help to double check and update. thanks.
The version in the play is 2.9.2, so bad impression.

**Comment by perssonmagnus** [comment]
Hi,

We are aware that there are some issues related to new permissions required in newer Android versions, and we are working on a fix for this.

Best Regards,
Magnus

**Comment by haso2007** [comment]
Good to hear that, but the 2.9.1 works fine. thanks for your prompt response




















At 2023-11-14 20:23:50, "Magnus Persson u-blox" ***@***.***> wrote:

Hi,

We are aware that there are some issues related to new permissions required in newer Android versions, and we are working on a fix for this.

Best Regards,
Magnus

**Comment by perssonmagnus** [comment]
Hello,

For your information we have just published, here and on Google Play store, version 2.9.3. This should resolve the issues with scanning found in v2.9.2.

I will close this issue, please open another one if you see other problems.

Best Regards,
Magnus

**Comment by haso2007** [comment]
Hello
      Wonderful. It works properly in my Samgsung S22 now. Thanks for your support.




















At 2023-11-22 22:16:18, "Magnus Persson u-blox" ***@***.***> wrote:

Hello,

For your information we have just published, here and on Google Play store, version 2.9.3. This should resolve the issues with scanning found in v2.9.2.

I will close this issue, please open another one if you see other problems.

Best Regards,
Magnus
